$(document).ready(function(){
    $("#developmentimage").click(function(){
      $("#developmentimage").slideDown('1500').hide('1000');
      $("#development").show('1500');
    });
    $("#development").click(function(){
      $("#development").slideUp('1500');
      $("#developmentimage").slideDown('1500');
    });
  });
  
  $(document).ready(function(){
    $("#designimage").click(function(){
      $("#designimage").slideDown('1500').hide('1000');
      $("#design").show('1500');
    });
    $("#design").click(function(){
      $("#design").slideUp('1500');
      $("#designimage").slideDown('1500');
    });
  });
  $(document).ready(function(){
    $("#designimage").click(function(){
      $("#designimage").slideDown('1500').hide('1000');
      $("#design").show('1500');
    });
    $("#design").click(function(){
      $("#design").slideUp('1500');
      $("#designimage").slideDown('1500');
    });
  });
  
  $(document).ready(function(){
    $("#product-image").click(function(){
      $("#product-image").slideDown('1500').hide('1000');
      $("#product").show('1500');
    });
    $("#product").click(function(){
      $("#product").slideUp('1500');
      $("#product-image").slideDown('1500');
    });
  });